"use client";

import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

export type LanguageCode = "en" | "hi" | "ta" | "te" | "bn" | "ml" | "kn" | "mr" | "gu" | "pa";

export interface Language {
    code: LanguageCode;
    name: string;
    nativeName: string;
}

export const LANGUAGES: Language[] = [
    { code: "en", name: "English", nativeName: "English" },
    { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
    { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
    { code: "te", name: "Telugu", nativeName: "తెలుగు" },
    { code: "bn", name: "Bengali", nativeName: "বাংলা" },
    { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
    { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
    { code: "mr", name: "Marathi", nativeName: "मराठी" },
    { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
    { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
];

const translations: Record<LanguageCode, Record<string, string>> = {
    en: {
        // Nav & Common
        "nav.home": "Home",
        "nav.explorer": "Explorer",
        "nav.orders": "Orders",
        "nav.settings": "Settings",
        "nav.dashboard_btn": "Merchant Dashboard",
        "nav.register_btn": "Register Your Shop",
        "nav.login_btn": "Login / Join",
        "nav.support": "Support",
        "common.back": "Back",
        "common.next": "Next Step",
        "common.save": "Save",
        "common.loading": "Loading...",
        "common.verified": "Verified Merchant",
        "common.search": "Search",
        "common.all": "All",

        // Settings
        "settings.title": "Settings",
        "settings.preferences": "Preferences",
        "settings.language": "Language",
        "settings.theme": "Dark Mode",
        "settings.logout": "Log Out",
        "settings.guest_title": "Welcome, Guest",
        "settings.guest_desc": "Join our community of local vendors",
        "settings.register_cta": "Register Store",
        "settings.notifications": "Notifications",
        "settings.appearance": "Appearance",
        "settings.privacy": "Privacy & Security",
        "settings.data_privacy": "Data & Privacy",
        "settings.manage_data": "Manage your data",
        "settings.shop_profile": "Shop Profile",
        "settings.manage_shop": "Manage shop details",
        "settings.setup_portfolio": "Setup your Shop Portfolio",
        "settings.join_streetlink": "Sign In / Join StreetLink",
        "settings.lang_select_title": "Select Language",
        "settings.lang_select_desc": "Choose your preferred language",
        "settings.enabled": "Enabled",
        "settings.disabled": "Disabled",
        "settings.guest_user": "Guest User",
        "settings.join_launch": "Join to launch your store",
        "settings.sys_default": "System default",

        // Landing
        "landing.title": "Local Heartbeat. Linked.",
        "landing.subtitle": "Connecting local vendors with modern shoppers. We digitize the street-side charm with power and elegance.",
        "landing.get_started": "Explore Markets",
        "landing.be_merchant": "Register Your Shop",

        // Dashboard
        "dashboard.title": "Merchant Portal",
        "dashboard.balance": "Total Balance",
        "dashboard.success_rate": "Success Rate",
        "dashboard.deliveries": "Deliveries",
        "dashboard.actions": "Quick Actions",
        "dashboard.add_product": "Add Product",
        "dashboard.qr_code": "Store QR Code",
        "dashboard.manage_inventory": "Manage inventory",
        "dashboard.share_shop": "Share your shop",
        "dashboard.view_all": "View all",
        "dashboard.no_orders": "No active orders",
        "dashboard.realtime": "Real-time updates active",
        "dashboard.ai_title": "AI Smart Insights",
        "dashboard.ai_desc": "Unlock localized trends, pricing analysis, and customer heatmaps to grow your business.",
        "dashboard.coming_soon": "Coming Soon",
        "dashboard.merchant_only": "Merchant Access Only",
        "dashboard.onboarding_req": "Complete the onboarding process to access your merchant dashboard.",
        "dashboard.register_now": "Register Now",
        "dashboard.download_qr": "Download QR",
        "dashboard.copy_link": "Copy Shop Link",
        "dashboard.copied": "Copied!",

        // Explorer
        "explorer.title": "Market Explorer",
        "explorer.nearby": "Nearby Shops",
        "explorer.placeholder": "Search tailors, grocers, repair shops...",
        "explorer.popular": "Popular Searches",
        "explorer.no_results": "No vendors found matching your high-performance criteria.",
        "explorer.nearby_desc": "Sorted by distance",
        "explorer.inventory_updates": "Check back soon for live inventory updates.",
        "explorer.shops_nearby": "Shops Nearby",
        "explorer.market_status": "Market Status",
        "explorer.live": "Live",
        "explorer.one_tap": "Every Local Shop, One Tap Away",
        "explorer.one_tap_desc": "From tailors to grocers, chai stalls to repair shops — discover & support vendors around you.",
        "explorer.your_neighbourhood": "Your Neighbourhood",
        "explorer.categories_stat": "Categories",

        // Support
        "support.title": "Help Center",
        "support.subtitle": "Support",
        "support.get_touch": "Get in Touch",
        "support.faq": "Frequently Asked Questions",
        "support.resources": "Resources",

        "support.contact.chat": "Live Chat",
        "support.contact.chat_desc": "Chat with our team",
        "support.contact.email": "Email Us",
        "support.contact.email_desc": "support@localynk.in",
        "support.contact.call": "Call Us",
        "support.contact.call_desc": "+91 1800-XXX-XXXX",

        "support.faq.q1": "How do I register my shop?",
        "support.faq.a1": "Go to the Register page and follow the 3-step onboarding process. It takes less than 60 seconds.",
        "support.faq.q2": "How do customers find my shop?",
        "support.faq.a2": "Once registered, your shop appears on the Market Explorer. Customers nearby can discover and order from you.",
        "support.faq.q3": "Is there a commission fee?",
        "support.faq.a3": "Localynk charges a minimal platform fee of 2% per transaction. No hidden charges.",
        "support.faq.q4": "How do I receive payments?",
        "support.faq.a4": "Payments are settled directly to your linked bank account within 24 hours of order completion.",
        "support.faq.q5": "Can I manage my inventory?",
        "support.faq.a5": "Yes! Use the Products page in your dashboard to add, edit, or remove items from your catalog.",

        "support.res.tos": "Terms of Service",
        "support.res.tos_desc": "Read our terms",
        "support.res.privacy": "Privacy Policy",
        "support.res.privacy_desc": "How we protect your data",

        // Onboarding
        "onboarding.step_of": "Step {0} of 3",
        "onboarding.merchant_title": "Merchant Onboarding",
        "onboarding.register": "Register",
        "onboarding.step1_title": "Your Digital Storefront",
        "onboarding.step1_desc": "Set up the basics for your shop.",
        "onboarding.shop_name": "Shop Name",
        "onboarding.what_sell": "What do you sell?",
        "onboarding.step2_title": "Identity & Reach",
        "onboarding.step2_desc": "Help customers find you on the map.",
        "onboarding.locate": "Auto-locate Shop",
        "onboarding.photo": "Upload Store Photo",
        "onboarding.step3_title": "Ready to Launch!",
        "onboarding.step3_desc": "Add your contact details & preferences.",
        "onboarding.phone": "Phone Number",
        "onboarding.email": "Email Address",
        "onboarding.upi": "UPI ID",
        "onboarding.launch": "Launch My Store",
        "onboarding.shop_error": "Shop name is required",
        "onboarding.cat_error": "Select at least one category",
        "onboarding.cat_custom_placeholder": "Describe what you sell...",
        "onboarding.cat_selected_count": "{0} categories selected",
        "onboarding.cat_selected_single": "1 category selected",
        "onboarding.address_error": "Unable to detect location. Please allow location access.",
        "onboarding.photo_success": "Photo Uploaded",
        "onboarding.photo_change": "Change Photo",
        "onboarding.photo_remove": "Remove Photo",
        "onboarding.next_step": "Next Step",
        "onboarding.custom_cat": "Describe what you sell...",

        // Shop View
        "shop.verified": "Verified Merchant",
        "shop.call": "Direct Call",
        "shop.chat": "WhatsApp Chat",
        "shop.rating": "Rating",
        "shop.happy_souls": "Happy Souls",
        "shop.service": "Service",
        "shop.produce_title": "High-Performance Produce",
        "shop.produce_desc": "Quality checked and ready for rapid local fulfillment.",
        "shop.empty": "Storefront Empty",
        "shop.checkout": "Secure Checkout",
        "shop.instant_support": "Instant support",
        "shop.quick_response": "Quick response",
        "shop.free": "FREE",
        "shop.fresh_stock": "Fresh Stock — {0}",
        "shop.empty_desc": "This vendor hasn't uploaded their products yet. Stay tuned for updates.",
        "shop.items_count": "{0} Items",
        "shop.total": "Total: ₹{0}",

        // Categories
        "cat.grocery": "Grocery",
        "cat.food": "Street Food",
        "cat.clothing": "Clothing",
        "cat.fruits": "Fruits",
        "cat.vegetables": "Vegetables",
        "cat.tailoring": "Tailoring",
        "cat.repair": "Repair",
        "cat.pharmacy": "Pharmacy",
        "cat.cafe": "Café & Tea",
        "cat.others": "Others"
    },
    hi: {
        "nav.home": "होम",
        "nav.explorer": "खोजें",
        "nav.orders": "ऑर्डर",
        "nav.settings": "सेटिंग्स",
        "nav.dashboard_btn": "मर्चेंट डैशबोर्ड",
        "nav.register_btn": "अपनी दुकान रजिस्टर करें",
        "nav.login_btn": "लॉगिन / शामिल हों",
        "nav.support": "सहायता",
        "common.back": "पीछे",
        "common.next": "अगला कदम",
        "common.save": "सुरक्षित करें",
        "common.loading": "लोड हो रहा है...",
        "common.verified": "सत्यापित मर्चेंट",
        "common.search": "खोजें",
        "common.all": "सभी",

        "settings.title": "सेटिंग्स",
        "settings.preferences": "वरीयताएं",
        "settings.language": "भाषा",
        "settings.theme": "डार्क मोड",
        "settings.logout": "लॉग आउट",
        "settings.guest_title": "नमस्ते, अतिथि",
        "settings.guest_desc": "हमारे स्थानीय विक्रेताओं के समुदाय में शामिल हों",
        "settings.register_cta": "स्टोर रजिस्टर करें",
        "settings.notifications": "नोटिफिकेशन",
        "settings.appearance": "दिखावट",
        "settings.privacy": "गोपनीयता और सुरक्षा",
        "settings.data_privacy": "डेटा और गोपनीयता",
        "settings.manage_data": "अपना डेटा प्रबंधित करें",
        "settings.shop_profile": "शॉप प्रोफ़ाइल",
        "settings.manage_shop": "दुकान का विवरण प्रबंधित करें",
        "settings.setup_portfolio": "अपनी शॉप पोर्टफोलियो सेटअप करें",
        "settings.join_streetlink": "साइन इन / स्ट्रीटलिंक में शामिल हों",
        "settings.lang_select_title": "भाषा चुनें",
        "settings.lang_select_desc": "अपनी पसंदीदा भाषा चुनें",
        "settings.enabled": "सक्षम",
        "settings.disabled": "अक्षम",
        "settings.guest_user": "अतिथि उपयोगकर्ता",
        "settings.join_launch": "अपना स्टोर लॉन्च करने के लिए जुड़ें",
        "settings.sys_default": "सिस्टम डिफॉल्ट",

        "landing.title": "स्थानीय धड़कन। जुड़ाव।",
        "landing.subtitle": "स्थानीय विक्रेताओं को आधुनिक खरीदारों से जोड़ना। हम सड़कों के जादू को आधुनिक तकनीक से जोड़ते हैं।",
        "landing.get_started": "बाजार देखें",
        "landing.be_merchant": "अपनी दुकान रजिस्टर करें",

        "dashboard.title": "मर्चेंट पोर्टल",
        "dashboard.balance": "कुल शेष",
        "dashboard.success_rate": "सफलता दर",
        "dashboard.deliveries": "डिलिवरी",
        "dashboard.actions": "त्वरित कार्रवाई",
        "dashboard.add_product": "उत्पाद जोड़ें",
        "dashboard.qr_code": "स्टोर QR कोड",
        "dashboard.manage_inventory": "सूची प्रबंधित करें",
        "dashboard.share_shop": "अपनी दुकान शेयर करें",
        "dashboard.view_all": "सभी देखें",
        "dashboard.no_orders": "कोई सक्रिय ऑर्डर नहीं",
        "dashboard.realtime": "रीयल-टाइम अपडेट सक्रिय",
        "dashboard.ai_title": "AI स्मार्ट अंतर्दृष्टि",
        "dashboard.ai_desc": "अपने व्यवसाय को बढ़ाने के लिए स्थानीय रुझान, मूल्य विश्लेषण और ग्राहक मानचित्र अनलॉक करें।",
        "dashboard.coming_soon": "जल्द आ रहा है",
        "dashboard.merchant_only": "केवल मर्चेंट एक्सेस",
        "dashboard.onboarding_req": "अपने मर्चेंट डैशबोर्ड तक पहुँचने के लिए ऑनबोर्डिंग प्रक्रिया पूरी करें।",
        "dashboard.register_now": "अभी रजिस्टर करें",
        "dashboard.download_qr": "QR डाउनलोड करें",
        "dashboard.copy_link": "लिंक कॉपी करें",
        "dashboard.copied": "कॉपी किया गया!",

        "explorer.title": "मार्केट एक्सप्लोरर",
        "explorer.nearby": "आस-पास की दुकानें",
        "explorer.placeholder": "दर्जी, किराना, मरम्मत की दुकानें खोजें...",
        "explorer.popular": "लोकप्रिय खोजें",
        "explorer.no_results": "आपकी खोज से मेल खाने वाले कोई विक्रेता नहीं मिले।",
        "explorer.nearby_desc": "दूरी के अनुसार क्रमबद्ध",
        "explorer.inventory_updates": "लाइव इन्वेंट्री अपडेट के लिए जल्द ही दोबारा देखें।",
        "explorer.shops_nearby": "आस-पास की दुकानें",
        "explorer.market_status": "मार्केट स्थिति",
        "explorer.live": "लाइव",
        "explorer.one_tap": "हर स्थानीय दुकान, बस एक टैप दूर",
        "explorer.one_tap_desc": "दर्जियों से लेकर किराना विक्रेताओं तक, चाय की दुकानों से लेकर मरम्मत की दुकानों तक — अपने आस-पास के विक्रेताओं को खोजें और उनका समर्थन करें।",
        "explorer.your_neighbourhood": "आपका पड़ोस",
        "explorer.categories_stat": "श्रेणियाँ",

        "support.title": "सहायता केंद्र",
        "support.subtitle": "सहायता",
        "support.get_touch": "संपर्क करें",
        "support.faq": "अक्सर पूछे जाने वाले प्रश्न",
        "support.resources": "संसाधन",

        "support.contact.chat": "लाइव चैट",
        "support.contact.chat_desc": "हमारी टीम से बात करें",
        "support.contact.email": "हमें ईमेल करें",
        "support.contact.email_desc": "support@localynk.in",
        "support.contact.call": "हमें कॉल करें",
        "support.contact.call_desc": "+91 1800-XXX-XXXX",

        "support.faq.q1": "मैं अपनी दुकान कैसे पंजीकृत करूं?",
        "support.faq.a1": "रजिस्टर पेज पर जाएं और 3-चरणीय ऑनबोर्डिंग प्रक्रिया का पालन करें। इसमें 60 सेकंड से भी कम समय लगता है।",
        "support.faq.q2": "ग्राहक मेरी दुकान कैसे ढूंढते हैं?",
        "support.faq.a2": "एक बार पंजीकृत होने के बाद, आपकी दुकान मार्केट एक्सप्लोरर पर दिखाई देती है। आस-पास के ग्राहक आपको ढूंढ सकते हैं और ऑर्डर दे सकते हैं।",
        "support.faq.q3": "क्या कोई कमीशन शुल्क है?",
        "support.faq.a3": "लोकलंक प्रति लेनदेन 2% का न्यूनतम प्लेटफॉर्म शुल्क लेता है। कोई छिपा हुआ शुल्क नहीं।",
        "support.faq.q4": "मुझे भुगतान कैसे प्राप्त होगा?",
        "support.faq.a4": "ऑर्डर पूरा होने के 24 घंटों के भीतर भुगतान सीधे आपके लिंक किए गए बैंक खाते में जमा कर दिया जाता है।",
        "support.faq.q5": "क्या मैं अपनी सूची प्रबंधित कर सकता हूँ?",
        "support.faq.a5": "हाँ! अपने डैशबोर्ड के उत्पाद पृष्ठ का उपयोग करके अपनी सूची में आइटम जोड़ें, संपादित करें या निकालें।",

        "support.res.tos": "सेवा की शर्तें",
        "support.res.tos_desc": "हमारी शर्तें पढ़ें",
        "support.res.privacy": "गोपनीयता नीति",
        "support.res.privacy_desc": "हम आपके डेटा की सुरक्षा कैसे करते हैं",

        "onboarding.step_of": "चरण {0} का 3",
        "onboarding.merchant_title": "मर्चेंट ऑनबोर्डिंग",
        "onboarding.register": "रजिस्टर",
        "onboarding.step1_title": "आपका डिजिटल स्टोर",
        "onboarding.step1_desc": "अपनी दुकान की बुनियादी जानकारी सेट करें।",
        "onboarding.shop_name": "दुकान का नाम",
        "onboarding.what_sell": "आप क्या बेचते हैं?",
        "onboarding.step2_title": "पहचान और पहुंच",
        "onboarding.step2_desc": "ग्राहकों को मानचित्र पर आपकी खोज में मदद करें।",
        "onboarding.locate": "दुकान की लोकेशन खोजें",
        "onboarding.photo": "स्टोर फोटो अपलोड करें",
        "onboarding.step3_title": "लॉन्च के लिए तैयार!",
        "onboarding.step3_desc": "अपना संपर्क विवरण और प्राथमिकताएं जोड़ें।",
        "onboarding.phone": "फोन नंबर",
        "onboarding.email": "ईमेल पता",
        "onboarding.upi": "UPI आईडी",
        "onboarding.launch": "मेरा स्टोर लॉन्च करें",
        "onboarding.shop_error": "दुकान का नाम आवश्यक है",
        "onboarding.cat_error": "कम से कम एक श्रेणी चुनें",
        "onboarding.cat_custom_placeholder": "बताएं कि आप क्या बेचते हैं...",
        "onboarding.cat_selected_count": "{0} श्रेणियां चुनी गईं",
        "onboarding.cat_selected_single": "1 श्रेणी चुनी गई",
        "onboarding.address_error": "स्थान का पता लगाने में असमर्थ। कृपया स्थान पहुंच की अनुमति दें।",
        "onboarding.photo_success": "फोटो अपलोड हो गई",
        "onboarding.photo_change": "फोटो बदलें",
        "onboarding.photo_remove": "फोटो हटाएं",
        "onboarding.next_step": "अगला कदम",
        "onboarding.custom_cat": "बताएं कि आप क्या बेचते हैं...",

        "shop.verified": "सत्यापित मर्चेंट",
        "shop.call": "सीधा कॉल",
        "shop.chat": "व्हाट्सएप चैट",
        "shop.rating": "रेटिंग",
        "shop.happy_souls": "खुश ग्राहक",
        "shop.service": "सेवा",
        "shop.produce_title": "उच्च गुणवत्ता वाले उत्पाद",
        "shop.produce_desc": "गुणवत्ता की जाँच की गई और तेजी से वितरण के लिए तैयार।",
        "shop.empty": "स्टोर खाली है",
        "shop.checkout": "सुरक्षित चेकआउट",
        "shop.instant_support": "त्वरित सहायता",
        "shop.quick_response": "तेज़ प्रतिक्रिया",
        "shop.free": "मुफ्त",
        "shop.fresh_stock": "ताजा स्टॉक — {0}",
        "shop.empty_desc": "इस विक्रेता ने अभी तक अपने उत्पाद अपलोड नहीं किए हैं। अपडेट के लिए बने रहें।",
        "shop.items_count": "{0} आइटम",
        "shop.total": "कुल: ₹{0}",

        "cat.grocery": "किराना",
        "cat.food": "स्ट्रीट फूड",
        "cat.clothing": "कपड़े",
        "cat.fruits": "फल",
        "cat.vegetables": "सब्जियां",
        "cat.tailoring": "सिलाई",
        "cat.repair": "मरम्मत",
        "cat.pharmacy": "फार्मेसी",
        "cat.cafe": "कैफे और चाय",
        "cat.others": "अन्य"
    },
    ta: {
        "nav.home": "முகப்பு",
        "nav.explorer": "ஆராயுங்கள்",
        "nav.orders": "ஆர்டர்கள்",
        "nav.settings": "அமைப்புகள்",
        "nav.dashboard_btn": "வணிகர் டாஷ்போர்டு",
        "nav.register_btn": "உங்கள் கடையை பதிவு செய்யுங்கள்",
        "nav.login_btn": "உள்நுழை / சேருங்கள்",
        "nav.support": "உதவி",
        "common.back": "பின்னால்",
        "common.next": "அடுத்த படி",
        "common.save": "சேமி",
        "common.loading": "ஏற்றுகிறது...",
        "common.verified": "அங்கீகரிக்கப்பட்ட வணிகர்",
        "common.search": "தேடு",
        "common.all": "அனைத்தும்",

        "settings.title": "அமைப்புகள்",
        "settings.preferences": "விருப்பத்தேர்வுகள்",
        "settings.language": "மொழி",
        "settings.theme": "இருண்ட முறை",
        "settings.logout": "வெளியேறு",
        "settings.guest_title": "வரவேற்கிறோம், விருந்தினரே",
        "settings.guest_desc": "எங்கள் உள்ளூர் வணிகர் குழுவில் இணையுங்கள்",
        "settings.register_cta": "கடையை பதிவு செய்க",
        "settings.notifications": "அறிவிப்புகள்",
        "settings.appearance": "தோற்றம்",
        "settings.privacy": "தனியுரிமை மற்றும் பாதுகாப்பு",
        "settings.data_privacy": "தரவு மற்றும் தனியுரிமை",
        "settings.manage_data": "உங்கள் தரவை நிர்வகிக்கவும்",
        "settings.shop_profile": "கடை விவரக்குறிப்பு",
        "settings.manage_shop": "கடை விவரங்களை நிர்வகிக்கவும்",
        "settings.setup_portfolio": "உங்கள் கடை போர்ட்ஃபோலியோவை அமைத்திடுங்கள்",
        "settings.join_streetlink": "உள்நுழை / ஸ்ட்ரீட்லிங்கில் சேருங்கள்",
        "settings.lang_select_title": "மொழியைத் தேர்ந்தெடுக்கவும்",
        "settings.lang_select_desc": "உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
        "settings.enabled": "இயக்கப்பட்டது",
        "settings.disabled": "முடக்கப்பட்டது",
        "settings.guest_user": "விருந்தினர் பயனர்",
        "settings.join_launch": "உங்கள் கடையைத் தொடங்க இணையுங்கள்",
        "settings.sys_default": "கணினி இயல்புநிலை",

        "landing.title": "உள்ளூர் துடிப்பு. இணைப்பு.",
        "landing.subtitle": "உள்ளூர் வணிகர்களை நவீன வாடிக்கையாளர்களுடன் இணைத்தல். தெருவோர அழகை நவீன தொழில்நுட்பத்துடன் இணைக்கிறோம்.",
        "landing.get_started": "சந்தையை ஆராயுங்கள்",
        "landing.be_merchant": "உங்கள் கடையை பதிவு செய்யுங்கள்",

        "dashboard.title": "வணிகர் தளம்",
        "dashboard.balance": "மொத்த இருப்பு",
        "dashboard.success_rate": "வெற்றி விகிதம்",
        "dashboard.deliveries": "டெலிவரிகள்",
        "dashboard.actions": "விரைவான செயல்கள்",
        "dashboard.add_product": "பொருளைச் சேர்",
        "dashboard.qr_code": "கடை QR குறியீடு",
        "dashboard.manage_inventory": "இருப்பை நிர்வகி",
        "dashboard.share_shop": "உங்கள் கடையைப் பகிரவும்",
        "dashboard.view_all": "அனைத்தையும் பார்",
        "dashboard.no_orders": "செயலில் உள்ள ஆர்டர்கள் இல்லை",
        "dashboard.realtime": "நேரடி புதுப்பிப்புகள் இயக்கத்தில் உள்ளன",
        "dashboard.ai_title": "AI நுண்ணறிவு",
        "dashboard.ai_desc": "உங்கள் வணிகத்தை வளர்க்க உள்ளூர் போக்குகள் மற்றும் விலை பகுப்பாய்வைத் தெரிந்துகொள்ளுங்கள்.",
        "dashboard.coming_soon": "விரைவில்",
        "dashboard.merchant_only": "வணிகர்களுக்கு மட்டும்",
        "dashboard.onboarding_req": "உங்கள் வணிகர் டாஷ்போர்டை அணுக பதிவு செயல்முறையை முடிக்கவும்.",
        "dashboard.register_now": "இப்போதே பதிவு செய்",
        "dashboard.download_qr": "QR ஐப் பதிவிறக்கு",
        "dashboard.copy_link": "லிங்க்கை நகலெடு",
        "dashboard.copied": "நகலெடுக்கப்பட்டது!",

        "explorer.title": "சந்தை ஆய்வு",
        "explorer.nearby": "அருகிலுள்ள கடைகள்",
        "explorer.placeholder": "தையல்காரர்கள், மளிகைக் கடைகள், பழுதுபார்க்கும் கடைகளைத் தேடுங்கள்...",
        "explorer.popular": "பிரபலமான தேடல்கள்",
        "explorer.no_results": "உங்கள் தேடலுக்கு ஏற்ற வணிகர்கள் யாரும் கிடைக்கவில்லை.",
        "explorer.nearby_desc": "தூரம் வாரியாக வரிசைப்படுத்தப்பட்டது",
        "explorer.inventory_updates": "நேரடி இருப்பு புதுப்பிப்புகளுக்கு விரைவில் பார்க்கவும்.",
        "explorer.shops_nearby": "அருகிலுள்ள கடைகள்",
        "explorer.market_status": "சந்தை நிலை",
        "explorer.live": "நேரலை",
        "explorer.one_tap": "ஒவ்வொரு உள்ளூர் கடையும், ஒரு தட்டல் தூரத்தில்",
        "explorer.one_tap_desc": "தையல்காரர்கள் முதல் மளிகை விற்பனையாளர்கள் வரை, தேநீர் கடைகள் முதல் பழுதுபார்க்கும் கடைகள் வரை — உங்களைச் சுற்றியுள்ள வணிகர்களைக் கண்டறிந்து ஆதரிக்கவும்.",
        "explorer.your_neighbourhood": "உங்கள் சுற்றுப்புறம்",
        "explorer.categories_stat": "வகைகள்",

        "support.title": "உதவி மையம்",
        "support.subtitle": "உதவி",
        "support.get_touch": "தொடர்பு கொள்ள",
        "support.faq": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
        "support.resources": "ஆதாரங்கள்",

        "support.contact.chat": "நேரடி அரட்டை",
        "support.contact.chat_desc": "எங்கள் குழுவுடன் பேசுங்கள்",
        "support.contact.email": "மின்னஞ்சல் அனுப்பவும்",
        "support.contact.email_desc": "support@localynk.in",
        "support.contact.call": "அழைக்கவும்",
        "support.contact.call_desc": "+91 1800-XXX-XXXX",

        "support.faq.q1": "என் கடையை எவ்வாறு பதிவு செய்வது?",
        "support.faq.a1": "பதிவுப் பக்கத்திற்குச் சென்று 3-படி ஆன்போர்டிங் செயல்முறையைப் பின்பற்றவும். இதற்கு 60 வினாடிகளுக்கும் குறைவாகவே ஆகும்.",
        "support.faq.q2": "வாடிக்கையாளர்கள் என் கடையை எப்படி கண்டுபிடிப்பார்கள்?",
        "support.faq.a2": "பதிவு செய்தவுடன், உங்கள் கடை மார்க்கெட் எக்ஸ்ப்ளோரரில் தோன்றும். அருகிலுள்ள வாடிக்கையாளர்கள் உங்களைக் கண்டுபிடித்து ஆர்டர் செய்யலாம்.",
        "support.faq.q3": "ஏதேனும் கமிஷன் கட்டணம் உள்ளதா?",
        "support.faq.a3": "லோக்கல்யங்க் ஒரு பரிவர்த்தனைக்கு 2% குறைந்தபட்ச பிளாட்பார்ம் கட்டணத்தை வசூலிக்கிறது. மறைமுகக் கட்டணங்கள் ஏதுமில்லை.",
        "support.faq.q4": "பணம் எனக்கு எப்படி கிடைக்கும்?",
        "support.faq.a4": "ஆர்டர் முடிந்த 24 மணி நேரத்திற்குள் உங்கள் வங்கி கணக்கிற்கு பணம் நேரடியாக அனுப்பப்படும்.",
        "support.faq.q5": "எனது இருப்பை நான் நிர்வகிக்க முடியுமா?",
        "support.faq.a5": "ஆம்! உங்கள் டேஷ்போர்டில் உள்ள தயாரிப்புகள் பக்கத்தைப் பயன்படுத்தி பொருட்களைச் சேர்க்கலாம், மாற்றலாம் அல்லது நீக்கலாம்.",

        "support.res.tos": "சேவை விதிமுறைகள்",
        "support.res.tos_desc": "விதிமுறைகளைப் படிக்கவும்",
        "support.res.privacy": "தனியுரிமைக் கொள்கை",
        "support.res.privacy_desc": "உங்கள் தரவை நாங்கள் எவ்வாறு பாதுகாக்கிறோம்",

        "onboarding.step_of": "படி {0} இல் 3",
        "onboarding.merchant_title": "வணிகர் பதிவு",
        "onboarding.register": "பதிவு",
        "onboarding.step1_title": "உங்கள் டிஜிட்டல் கடை",
        "onboarding.step1_desc": "உங்கள் கடையின் அடிப்படை அமைப்புகளைச் செய்யவும்.",
        "onboarding.shop_name": "கடையின் பெயர்",
        "onboarding.what_sell": "நீங்கள் எதை விற்பனை செய்கிறீர்கள்?",
        "onboarding.step2_title": "அடையாளம் மற்றும் இருப்பிடம்",
        "onboarding.step2_desc": "வாடிக்கையாளர்கள் வரைபடத்தில் உங்களைக் கண்டறிய உதவுங்கள்.",
        "onboarding.locate": "இருப்பிடத்தைக் கண்டறி",
        "onboarding.photo": "கடை புகைப்படத்தைப் பதிவேற்றவும்",
        "onboarding.step3_title": "தொடங்க தயார்!",
        "onboarding.step3_desc": "உங்கள் தொடர்பு விவரங்கள் மற்றும் விருப்பங்களைச் சேர்க்கவும்.",
        "onboarding.phone": "தொலைபேசி எண்",
        "onboarding.email": "மின்னஞ்சல் முகவரி",
        "onboarding.upi": "UPI ஐடி",
        "onboarding.launch": "எனது கடையைத் தொடங்கு",
        "onboarding.shop_error": "கடையின் பெயர் தேவை",
        "onboarding.cat_error": "குறைந்தது ஒரு வகையைத் தேர்ந்தெடுக்கவும்",
        "onboarding.cat_custom_placeholder": "நீங்கள் எதை விற்பனை செய்கிறீர்கள் என்று விவரிக்கவும்...",
        "onboarding.cat_selected_count": "{0} வகைகள் தேர்ந்தெடுக்கப்பட்டன",
        "onboarding.cat_selected_single": "1 வகை தேர்ந்தெடுக்கப்பட்டது",
        "onboarding.address_error": "இருப்பிடத்தைக் கண்டறிய முடியவில்லை. இருப்பிட அனுமதியை வழங்கவும்.",
        "onboarding.photo_success": "புகைப்படம் பதிவேற்றப்பட்டது",
        "onboarding.photo_change": "புகைப்படத்தை மாற்றவும்",
        "onboarding.photo_remove": "புகைப்படத்தை அகற்றவும்",
        "onboarding.next_step": "அடுத்த படி",
        "onboarding.custom_cat": "நீங்கள் எதை விற்பனை செய்கிறீர்கள் என்று விவரிக்கவும்...",

        "shop.verified": "அங்கீகரிக்கப்பட்ட வணிகர்",
        "shop.call": "நேரடி அழைப்பு",
        "shop.chat": "வாட்ஸ்அப் அரட்டை",
        "shop.rating": "மதிப்பீடு",
        "shop.happy_souls": "மகிழ்ச்சியான வாடிக்கையாளர்கள்",
        "shop.service": "சேவை",
        "shop.produce_title": "உயர்தர தயாரிப்புகள்",
        "shop.produce_desc": "தரம் சரிபார்க்கப்பட்டு விரைவான டெலிவரிக்கு தயார்.",
        "shop.empty": "கடை காலியாக உள்ளது",
        "shop.checkout": "பாதுகாப்பான செக்அவுட்",
        "shop.instant_support": "உடனடி உதவி",
        "shop.quick_response": "விரைவான பதில்",
        "shop.free": "இலவசம்",
        "shop.fresh_stock": "புதிய இருப்பு — {0}",
        "shop.empty_desc": "இந்த வணிகர் இன்னும் பொருட்களைப் பதிவேற்றவில்லை. காத்திருங்கள்.",
        "shop.items_count": "{0} பொருட்கள்",
        "shop.total": "மொத்தம்: ₹{0}",

        "cat.grocery": "மளிகை",
        "cat.food": "தெரு உணவு",
        "cat.clothing": "உடை",
        "cat.fruits": "பழங்கள்",
        "cat.vegetables": "காய்கறிகள்",
        "cat.tailoring": "தையல்",
        "cat.repair": "பழுதுபார்ப்பு",
        "cat.pharmacy": "மருந்தகம்",
        "cat.cafe": "கஃபே மற்றும் டீ",
        "cat.others": "மற்றவை"
    },
    te: {
        "nav.home": "హోమ్",
        "nav.explorer": "అన్వేషించండి",
        "nav.orders": "ఆర్డర్లు",
        "nav.settings": "సెట్టింగ్‌లు",
        "nav.dashboard_btn": "మర్చంట్ డాష్‌బోర్డ్",
        "nav.register_btn": "మీ దుకాణాన్ని నమోదు చేయండి",
        "nav.login_btn": "లాగిన్ / చేరండి",
        "nav.support": "సహాయం",
        "common.back": "వెనుకకు",
        "common.next": "తదుపరి దశ",
        "common.save": "సేవ్",
        "common.loading": "లోడ్ అవుతోంది...",
        "common.verified": "ధృవీకరించబడిన వ్యాపారి",
        "common.search": "వెతకండి",
        "common.all": "అన్నీ",

        "settings.title": "సెట్టింగ్‌లు",
        "settings.preferences": "ప్రాధాన్యతలు",
        "settings.language": "భాష",
        "settings.theme": "డార్క్ మోడ్",
        "settings.logout": "లాగ్ అవుట్",
        "settings.guest_title": "స్వాగతం, అతిథి",
        "settings.guest_desc": "స్థానిక వ్యాపారుల సంఘంలో చేరండి",
        "settings.register_cta": "స్టోర్‌ను నమోదు చేయండి",
        "settings.notifications": "నోటిఫికేషన్‌లు",
        "settings.appearance": "రూపాంతరం",
        "settings.privacy": "గోప్యత మరియు భద్రత",
        "settings.data_privacy": "డేటా మరియు గోప్యత",
        "settings.manage_data": "మీ డేటాను నిర్వహించండి",
        "settings.shop_profile": "షాప్ ప్రొఫైల్",
        "settings.manage_shop": "దుకాణం వివరాలను నిర్వహించండి",
        "settings.setup_portfolio": "మీ షాప్ పోర్ట్‌ఫోలియోను సెటప్ చేయండి",
        "settings.join_streetlink": "సైన్ ఇన్ / స్ట్రీట్‌లింక్‌లో చేరండి",
        "settings.lang_select_title": "భాషను ఎంచుకోండి",
        "settings.lang_select_desc": "మీకు నచ్చిన భాషను ఎంచుకోండి",
        "settings.enabled": "ప్రారంభించబడింది",
        "settings.disabled": "నిలిపివేయబడింది",
        "settings.guest_user": "అతిథి వినియోగదారు",
        "settings.join_launch": "మీ దుకాణాన్ని ప్రారంభించడానికి చేరండి",
        "settings.sys_default": "సిస్టమ్ డిఫాల్ట్",

        "landing.title": "స్థానిక హృదయస్పందన. అనుసంధానం.",
        "landing.subtitle": "స్థానిక వ్యాపారులను ఆధునిక వినియోగదారులతో అనుసంధానించడం. మేము వీధి ఆహ్లాదాన్ని ఆధునిక సాంకేతికతతో డిజిటలైజ్ చేస్తాము.",
        "landing.get_started": "మార్కెట్‌లను అన్వేషించండి",
        "landing.be_merchant": "మీ దుకాణాన్ని నమోదు చేయండి",

        "dashboard.title": "మర్చంట్ పోర్టల్",
        "dashboard.balance": "మొత్తం బ్యాలెన్స్",
        "dashboard.success_rate": "విజయ రేటు",
        "dashboard.deliveries": "డెలివరీలు",
        "dashboard.actions": "త్వరిత చర్యలు",
        "dashboard.add_product": "ఉత్పత్తిని జోడించు",
        "dashboard.qr_code": "స్టోర్ QR కోడ్",
        "dashboard.manage_inventory": "జాబితాను నిర్వహించండి",
        "dashboard.share_shop": "మీ దుకాణాన్ని షేర్ చేయండి",
        "dashboard.view_all": "అన్నీ చూడండి",
        "dashboard.no_orders": "క్రియాశీల ఆర్డర్‌లు లేవు",
        "dashboard.realtime": "రియల్-టైమ్ అప్‌డేట్‌లు సక్రియంగా ఉన్నాయి",
        "dashboard.ai_title": "AI స్మార్ట్ అంతర్దృష్టులు",
        "dashboard.ai_desc": "మీ వ్యాపారాన్ని పెంచుకోవడానికి స్థానిక ట్రెండ్‌లు, ధరల విశ్లేషణ మరియు కస్టమర్ హీట్‌మ్యాప్‌లను అన్‌లాక్ చేయండి.",
        "dashboard.coming_soon": "త్వరలో",
        "dashboard.merchant_only": "వ్యాపారులకు మాత్రమే ప్రవేశం",
        "dashboard.onboarding_req": "మీ మర్చంట్ డాష్‌బోర్డ్‌ను యాక్సెస్ చేయడానికి ఆన్‌బోర్డింగ్ ప్రక్రియను పూర్తి చేయండి.",
        "dashboard.register_now": "ఇప్పుడే నమోదు చేసుకోండి",
        "dashboard.download_qr": "QR డౌన్‌లోడ్ చేయండి",
        "dashboard.copy_link": "లింక్ కాపీ చేయండి",
        "dashboard.copied": "కాపీ చేయబడింది!",

        "explorer.title": "మార్కెట్ ఎక్స్‌ప్లోరర్",
        "explorer.nearby": "సమీపంలోని దుకాణాలు",
        "explorer.placeholder": "Tailors, grocers, రిపేర్ షాపుల కోసం వెతకండి...",
        "explorer.popular": "ప్రముఖ శోధనలు",
        "explorer.no_results": "మీ శోధనకు సరిపోయే వ్యాపారులు ఎవరూ లేరు.",
        "explorer.nearby_desc": "దూరం ప్రకారం క్రమబద్ధీకరించబడింది",
        "explorer.inventory_updates": "లైవ్ ఇన్వెంటరీ అప్‌డేట్‌ల కోసం త్వరలో మళ్ళీ చూడండి.",
        "explorer.shops_nearby": "సమీపంలోని దుకాణాలు",
        "explorer.market_status": "మార్కెట్ స్థితి",
        "explorer.live": "లైవ్",
        "explorer.one_tap": "ప్రతి స్థానిక దుకాణం, కేవలం ఒక ట్యాప్ దూరంలో",
        "explorer.one_tap_desc": "దర్జీల నుండి కిరాణా వ్యాపారుల వరకు, టీ స్టాళ్ల నుండి రిపేర్ షాపుల వరకు — మీ చుట్టూ ఉన్న వ్యాపారులను కనుగొనండి మరియు మద్దతు ఇవ్వండి.",
        "explorer.your_neighbourhood": "మీ పొరుగు ప్రాంతం",
        "explorer.categories_stat": "వర్గాలు",

        "support.title": "సహాయ కేంద్రం",
        "support.subtitle": "సహాయం",
        "support.get_touch": "సంప్రదించండి",
        "support.faq": "తరచుగా అడిగే ప్రశ్నలు",
        "support.resources": "వనరులు",

        "support.contact.chat": "లైవ్ చాట్",
        "support.contact.chat_desc": "మా బృందంతో చాట్ చేయండి",
        "support.contact.email": "మాకు ఈమెయిల్ చేయండి",
        "support.contact.email_desc": "support@localynk.in",
        "support.contact.call": "మాకు కాల్ చేయండి",
        "support.contact.call_desc": "+91 1800-XXX-XXXX",

        "support.faq.q1": "నా దుకాణాన్ని ఎలా నమోదు చేయాలి?",
        "support.faq.a1": "రిజిస్టర్ పేజీకి వెళ్లి 3-దశల ఆన్‌బోర్డింగ్ ప్రక్రియను అనుసరించండి. దీనికి 60 సెకన్ల కంటే తక్కువ సమయం పడుతుంది.",
        "support.faq.q2": "కస్టమర్లు నా దుకాణాన్ని ఎలా కనుగొంటారు?",
        "support.faq.a2": "నమోదు చేసుకున్న తర్వాత, మీ దుకాణం మార్కెట్ ఎక్స్‌ప్లోరర్‌లో కనిపిస్తుంది. సమీపంలోని కస్టమర్లు మిమ్మల్ని కనుగొని ఆర్డర్ చేయవచ్చు.",
        "support.faq.q3": "కమీషన్ రుసుము ఉందా?",
        "support.faq.a3": "లోకల్‌యంక్ ప్రతి లావాదేవీకి 2% కనీస ప్లాట్‌ఫారమ్ రుసుమును వసూలు చేస్తుంది. దాచిన ఛార్జీలు లేవు.",
        "support.faq.q4": "నేను చెల్లింపులను ఎలా స్వీకరించాలి?",
        "support.faq.a4": "ఆర్డర్ పూర్తయిన 24 గంటలలోపు మీ బ్యాంక్ ఖాతాకు నేరుగా చెల్లింపులు చేయబడతాయి.",
        "support.faq.q5": "నేను నా ఇన్వెంటరీని నిర్వహించవచ్చా?",
        "support.faq.a5": "అవును! మీ డ్యాష్‌బోర్డ్‌లోని ఉత్పత్తుల పేజీని ఉపయోగించి మీ కేటలాగ్ నుండి వస్తువులను జోడించవచ్చు, సవరించవచ్చు లేదా తొలగించవచ్చు.",

        "support.res.tos": "సేవా నిబంధనలు",
        "support.res.tos_desc": "మా నిబంధనలను చదవండి",
        "support.res.privacy": "గోప్యతా విధానం",
        "support.res.privacy_desc": "మేము మీ డేటాను ఎలా రక్షిస్తాము",

        "onboarding.step_of": "దశ {0} లో 3",
        "onboarding.merchant_title": "మర్చంట్ ఆన్‌బోర్డింగ్",
        "onboarding.register": "రిజిస్టర్",
        "onboarding.step1_title": "మీ డిజిటల్ స్టోర్ ఫ్రంట్",
        "onboarding.step1_desc": "మీ దుకాణం కోసం ప్రాథమికాలను సెటప్ చేయండి.",
        "onboarding.shop_name": "దుకాణం పేరు",
        "onboarding.what_sell": "మీరు ఏమి విక్రయిస్తారు?",
        "onboarding.step2_title": "గుర్తింపు మరియు పరిధి",
        "onboarding.step2_desc": "వినియోగదారులు మిమ్మల్ని మ్యాప్‌లో కనుగొనడంలో సహాయపడండి.",
        "onboarding.locate": "దుకాణం స్థానాన్ని గుర్తించు",
        "onboarding.photo": "స్టోర్ ఫోటోను అప్‌లోడ్ చేయండి",
        "onboarding.step3_title": "ప్రారంభానికి సిద్ధంగా ఉంది!",
        "onboarding.step3_desc": "మీ సంప్రదింపు వివరాలు మరియు ప్రాధాన్యతలను జోడించండి.",
        "onboarding.phone": "ఫోన్ నంబర్",
        "onboarding.email": "ఈమెయిల్ చిరునామా",
        "onboarding.upi": "UPI ID",
        "onboarding.launch": "నా స్టోర్‌ను ప్రారంభించు",
        "onboarding.shop_error": "దుకాణం పేరు అవసరం",
        "onboarding.cat_error": "కనీసం ఒక వర్గాన్ని ఎంచుకోండి",
        "onboarding.cat_custom_placeholder": "మీరు ఏమి విక్రయిస్తారో వివరించండి...",
        "onboarding.cat_selected_count": "{0} వర్గాలు ఎంచుకోబడ్డాయి",
        "onboarding.cat_selected_single": "1 వర్గం ఎంచుకోబడింది",
        "onboarding.address_error": "స్థానాన్ని గుర్తించలేకపోయాము. దయచేసి స్థాన అనుమతిని ఇవ్వండి.",
        "onboarding.photo_success": "ఫోటో అప్‌లోడ్ చేయబడింది",
        "onboarding.photo_change": "ఫోటో మార్చండి",
        "onboarding.photo_remove": "ఫోటో తీసివేయండి",
        "onboarding.next_step": "తదుపరి దశ",
        "onboarding.custom_cat": "మీరు ఏమి విక్రయిస్తారో వివరించండి...",

        "shop.verified": "ధృవీకరించబడిన వ్యాపారి",
        "shop.call": "నేరుగా కాల్ చేయండి",
        "shop.chat": "వాట్సాప్ చాట్",
        "shop.rating": "రేటింగ్",
        "shop.happy_souls": "సంతోషకరమైన కస్టమర్లు",
        "shop.service": "సేవ",
        "shop.produce_title": "అధిక నాణ్యత కలిగిన ఉత్పత్తులు",
        "shop.produce_desc": "నాణ్యత పరీక్షించబడింది మరియు వేగవంతమైన డెలివరీకి సిద్ధంగా ఉంది.",
        "shop.empty": "స్టోర్ ఖాళీగా ఉంది",
        "shop.checkout": "సురక్షిత చెక్అవుట్",
        "shop.instant_support": "తక్షణ మద్దతు",
        "shop.quick_response": "వేగవంతమైన ప్రతిస్పందన",
        "shop.free": "ఉచితం",
        "shop.fresh_stock": "తాజా స్టాక్ — {0}",
        "shop.empty_desc": "ఈ వ్యాపారి ఇంకా తమ ఉత్పత్తులను అప్‌లోడ్ చేయలేదు. అప్‌డేట్‌ల కోసం చూస్తూ ఉండండి.",
        "shop.items_count": "{0} వస్తువులు",
        "shop.total": "మొత్తం: ₹{0}",

        "cat.grocery": "కిరాణా",
        "cat.food": "వీధి ఆహారం",
        "cat.clothing": "దుస్తులు",
        "cat.fruits": "పండ్లు",
        "cat.vegetables": "కూరగాయలు",
        "cat.tailoring": "టైలరింగ్",
        "cat.repair": "రిపేర్",
        "cat.pharmacy": "ఫార్మసీ",
        "cat.cafe": "కాఫీ మరియు టీ",
        "cat.others": "ఇతరాలు"
    },
    bn: {}, ml: {}, kn: {}, mr: {}, gu: {}, pa: {}
};

// Fill empty with English defaults to avoid breaking UI
Object.keys(translations).forEach((code) => {
    const lang = code as LanguageCode;
    if (lang !== "en") {
        Object.keys(translations.en).forEach((key) => {
            if (!translations[lang][key]) {
                translations[lang][key] = translations.en[key];
            }
        });
    }
});

interface LanguageContextType {
    langCode: LanguageCode;
    language: Language;
    setLanguage: (code: LanguageCode) => void;
    t: (key: string, ...args: any[]) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [langCode, setLangCode] = useState<LanguageCode>("en");

    useEffect(() => {
        const savedLang = localStorage.getItem("app-language") as LanguageCode;
        if (savedLang && translations[savedLang]) {
            setLangCode(savedLang);
        }
    }, []);

    const setLanguage = (code: LanguageCode) => {
        setLangCode(code);
        localStorage.setItem("app-language", code);
    };

    const t = useCallback((key: string, ...args: any[]) => {
        let text = translations[langCode][key] || translations["en"][key] || key;
        if (args.length > 0) {
            args.forEach((arg, i) => {
                text = text.replace(`{${i}}`, arg);
            });
        }
        return text;
    }, [langCode]);

    const language = LANGUAGES.find(l => l.code === langCode) || LANGUAGES[0];

    return (
        <LanguageContext.Provider value={{ langCode, language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
